name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_TEST }}
      - name: Run API tests
        run: |
          postman collection run "13240223-a0e51f15-9d80-4857-94f1-4a1a624f9d70" --integration-id "170245-${{ github.run_id }}"
